#
# Makefile
# haroldo, 2019-09-20 21:20
#

all:
	pdflatex python-mip-tutorial-podes ; bibtex python-mip-tutorial-podes ; pdflatex python-mip-tutorial-podes ; pdflatex python-mip-tutorial-podes


# vim:ft=make
#
