#
# Makefile
# haroldo, 2019-09-20 21:20
#

all:
	pdflatex -shell-escape python-mip-tutorial-podes  ; bibtex python-mip-tutorial-podes ; pdflatex -shell-escape python-mip-tutorial-podes ; pdflatex -shell-escape python-mip-tutorial-podes


# vim:ft=make
#
